### ISSUE TITLE
Full Stack project review

### ISSUE THREAD

**Issue by Jakousa** [tranjt/aprotracker#1]
# Full Stack project review

Here's a short review of your Full Stack course project. The comments in the review are suggestions that you can use in this project or in your future projects. None of the suggestions are required to get a passing grade.

## Code ##

The code quality is high. The only issues I found were minimal.

https://github.com/tranjt/aprotracker/blob/f06909a2327fb527e2ee504641f29115a8d29e4b/aprotrackerFrontend/src/components/workout/RoutineOptions.jsx#L24-L32

Above, guard clause is often used instead, so that the special cases are handled prior to the "successful route". In react components you often use this with `return null`. Here the guard clause would look like
```
if (!completedRoutine) return null

return (
  <Text style={styles.date}>
    last completed:
    {dateFormat(completedRoutine.createdAt)}
  </Text>
);
```
https://github.com/tranjt/aprotracker/blob/f06909a2327fb527e2ee504641f29115a8d29e4b/aprotrackerFrontend/src/components/workout/RoutineOptions.jsx#L24-L32

This could probably be rewritten https://github.com/tranjt/aprotracker/blob/f06909a2327fb527e2ee504641f29115a8d29e4b/aprotrackerFrontend/src/components/profile/ProfileScreen.jsx#L36-L66

You've structured the repository well and it's easy to find what I'm looking for but you should not have two components in a single file https://github.com/tranjt/aprotracker/blob/f06909a2327fb527e2ee504641f29115a8d29e4b/aprotrackerFrontend/src/components/signIn/SignIn.jsx#L25-L57

## Conclusion ##

Unfortunately I didn't get the app working. But your code is of high quality, well done! I hope you keep working with this project and get to release it to real users.

**Comment by tranjt** [comment]
The app not working is probably because I am running the back end locally on my pc and it haven't been on for quite a while. Thank you for the review and advices.
